consumer:
  enabled: true
  bootstrap-servers: localhost:9092
  retry-options:
    consumer-max-retries: 3
    operation-max-retries: 4
    backoff-factor: 5
  auth:
    enabled: false
log:
  level: "debug"
