consumer:
  enabled: true
  bootstrap-servers: localhost:9092
  retry-options:
    consumer-max-retries: 3
    operation-max-retries: 4
    backoff-factor: 5
  auth:
    enabled: false
storage:
  disable-persistence: false
  max-serialization-retries: 10
  database: postgres
  postgres:
    host: "localhost"
    port: "5433"
    user: "postgres"
    password: "yPsw5e6ab4bvAGe5H"
    dbname: "spicedb"
client:
  enabled: false
  url: "localhost:8000"
  enable-oidc-auth: false
  insecure: true
log:
  level: "debug"
